# Etapa 1: Construção da aplicação
FROM golang:1.20-alpine AS builder

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o módulo go e o sumário
COPY go.mod go.sum ./

# Baixar dependências
RUN go mod download

# Copiar o código-fonte
COPY . .

# Construir a aplicação
RUN go build -o app ./cmd

# Etapa 2: Execução da aplicação
FROM alpine:latest

# Instalar certificados SSL
RUN apk --no-cache add ca-certificates

# Definir o diretório de trabalho
WORKDIR /root/

# Copiar a aplicação compilada da etapa anterior
COPY --from=builder /app/app .

# Expor a porta em que a aplicação roda
EXPOSE 8080

# Comando para executar a aplicação
CMD ["./app"]
